@echo off
title Prompt Battle WebGame - Quick Start
color 0A

echo.
echo ==========================================
echo   PROMPT BATTLE WEBGAME - QUICK START
echo ==========================================
echo.

:menu
echo Choose startup option:
echo.
echo [1] Local only (localhost:3000)
echo [2] Local + ngrok (public access)
echo [3] ngrok only (server already running)
echo [4] Setup ngrok authtoken
echo [5] Setup ngrok domain configuration
echo [6] Kill all Node processes
echo [7] Show network info
echo [0] Exit
echo.

set /p choice="Enter your choice (0-7): "

if "%choice%"=="1" goto local
if "%choice%"=="2" goto local-ngrok
if "%choice%"=="3" goto ngrok-only
if "%choice%"=="4" goto setup-ngrok
if "%choice%"=="5" goto setup-domain
if "%choice%"=="6" goto kill
if "%choice%"=="7" goto network
if "%choice%"=="0" goto exit
goto menu

:local
echo.
echo Starting local server...
echo.
cd ..
cd backend
start "Prompt Battle Server" cmd /k "node server.js"
echo Server starting on http://localhost:3000
echo.
echo Press any key to return to menu...
pause
cd ..
cd start
goto menu

:local-ngrok
echo.
echo Starting local server + ngrok with reserved domain...
echo.

REM Load ngrok configuration
if not exist "..\ngrok.env" (
    echo ERROR: ngrok.env file not found!
    echo Please create ngrok.env file in the project root directory.
    echo See ngrok.env.example for template.
    echo.
    pause
    goto menu
)

REM Read domain from ngrok.env (get first non-empty NGROK_DOMAIN)
for /f "usebackq tokens=2 delims==" %%i in (`findstr /c:"NGROK_DOMAIN" "..\ngrok.env"`) do (
    if not "%%i"==" " (
        if not "%%i"=="" (
            set NGROK_DOMAIN=%%i
            goto domain_found
        )
    )
)

:domain_found
if "%NGROK_DOMAIN%"=="" (
    echo ERROR: NGROK_DOMAIN not set in ngrok.env
    echo.
    pause
    goto menu
)

echo Starting local server...
cd ..
cd backend
start "Prompt Battle Server" cmd /k "node server.js"
echo Waiting for server to start...
timeout /t 3 /nobreak > nul
cd ..
echo Starting ngrok tunnel...
start "ngrok Tunnel" cmd /k "ngrok.exe http 3000 --domain=%NGROK_DOMAIN%"
echo.
echo Server starting on http://localhost:3000
echo ngrok tunnel starting with domain: %NGROK_DOMAIN%
echo.
echo Your game will be available at: https://%NGROK_DOMAIN%
echo.
echo Press any key to return to menu...
pause
cd start
goto menu

:ngrok-only
echo.
echo Starting ngrok tunnel with reserved domain...
echo.

REM Load ngrok configuration
if not exist "..\ngrok.env" (
    echo ERROR: ngrok.env file not found!
    echo Please create ngrok.env file in the project root directory.
    echo See ngrok.env.example for template.
    echo.
    pause
    goto menu
)

REM Read domain from ngrok.env (get first non-empty NGROK_DOMAIN)
for /f "usebackq tokens=2 delims==" %%i in (`findstr /c:"NGROK_DOMAIN" "..\ngrok.env"`) do (
    if not "%%i"==" " (
        if not "%%i"=="" (
            set NGROK_DOMAIN=%%i
            goto domain_found2
        )
    )
)

:domain_found2
if "%NGROK_DOMAIN%"=="" (
    echo ERROR: NGROK_DOMAIN not set in ngrok.env
    echo.
    pause
    goto menu
)

cd ..
start "ngrok Tunnel" cmd /k "ngrok.exe http 3000 --domain=%NGROK_DOMAIN%"
echo ngrok tunnel starting with domain: %NGROK_DOMAIN%
echo.
echo Your game will be available at: https://%NGROK_DOMAIN%
echo.
echo Press any key to return to menu...
pause
cd start
goto menu

:setup-ngrok
echo.
echo Setting up ngrok authtoken...
echo.
echo 1. Go to: https://dashboard.ngrok.com/get-started/your-authtoken
echo 2. Copy your authtoken
echo 3. Paste it below
echo.
set /p authtoken="Enter your ngrok authtoken: "
ngrok.exe config add-authtoken %authtoken%
echo.
echo ngrok authtoken configured!
echo You can now use options 2 and 3 for public access.
echo.
pause
goto menu

:setup-domain
echo.
echo Setting up ngrok domain configuration...
echo.
echo This will create/update your ngrok.env file with your reserved domain.
echo.
echo 1. Make sure you have a reserved domain from: https://dashboard.ngrok.com/cloud-edge/domains
echo 2. Enter your domain below (without https://)
echo    Example: abiotic-hypogynous-akilah.ngrok-free.app
echo.
set /p domain="Enter your reserved ngrok domain: "
set /p authtoken="Enter your ngrok authtoken: "

echo # ngrok Configuration > ..\ngrok.env
echo # Generated by start-game.bat setup >> ..\ngrok.env
echo NGROK_AUTHTOKEN=%authtoken% >> ..\ngrok.env
echo NGROK_DOMAIN=%domain% >> ..\ngrok.env

echo.
echo ngrok.env file created successfully!
echo Domain: %domain%
echo.
echo You can now use options 2 and 3 with your reserved domain.
echo Your game will always be available at: https://%domain%
echo.
pause
goto menu

:kill
echo.
echo Killing all Node processes...
taskkill /f /im node.exe 2>nul
echo All Node processes stopped
echo.
pause
goto menu

:network
echo.
echo Network Information:
echo.
ipconfig | findstr "IPv4"
echo.
echo Your game can be accessed at:
echo http://YOUR_IP:3000 (replace YOUR_IP with the address above)
echo.
pause
goto menu

:exit
echo.
echo Goodbye!
timeout /t 2 /nobreak > nul
exit
